import type { Metadata } from "next";
import "./globals.css";
import SessionWrapper from "@/components/auth/SessionWrapper";
import { ThemeProvider } from "@/providers/theme-provider";
import ToasterProvider from "@/providers/toast-providers";
export const metadata: Metadata = {
  title: "NotesAcademy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en" suppressHydrationWarning>
        <body>
          <ToasterProvider/>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false} disableTransitionOnChange>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </SessionWrapper>
  );
}
